name: touristic_lines
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.6.1
  equatable: ^2.0.5
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  camera: ^0.11.3
  yandex_mapkit: ^4.2.1
  geolocator: ^14.0.2
  gpx: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/street_icons/Decabristov_street.jpg
    - assets/street_icons/Green_street.jpg
    - assets/street_icons/Bagulov_street.jpg
    - assets/street_icons/Red_street.jpg
    - assets/icons/ic_pin.png
    - assets/icons/bagulova_line_pin.png
    - assets/icons/green_street_pin.png
    - assets/icons/decabristov_street_pin.png
    - assets/icons/red_street_pin.png